### ISSUE TITLE
图文效果展示？

### ISSUE THREAD

**Issue by roachsinai** [igo312/Message-Board-of-WeChat#4]
有没有图文效果展示呢？还有期待第一个release！😃

**Comment by roachsinai** [comment]
emmm，看到了。

先感谢，不过还没有接触小程序开发。

**Comment by igo312** [comment]
你好，已经添加图文效果的展示。小程序目前已发布，但是只有在公众号内可以进入留言板留言呢 😃

**Comment by roachsinai** [comment]
所以，公众号是？

**Comment by igo312** [comment]
饼子屋，在最新的文章里会有留言板的功能。冒昧地问一句，我对github不熟悉，当我更新仓库的时候你那边会收到通知么？

**Comment by roachsinai** [comment]
关注了。右上角有watch, star, fork。如果watch的话，任何有关这个repo的事件都会收到通知：有人提issue, 提PR, 你有新提交之类。

**Comment by roachsinai** [comment]
右上角有watch, star, fork。如果点了watch的话，任何有关这个repo的事件都会收到通知：有人提issue, 提PR, 你有新提交之类。

**Comment by igo312** [comment]
好的，十分抱歉更新过多带来的打扰。

**Comment by roachsinai** [comment]
那没有。😃
