### ISSUE TITLE
请问一下关于留言功能属于社交范畴，只有企业资质的小程序号才可以发布这个问题你是怎么解决的呢？

### ISSUE THREAD

**Issue by Ezereal** [igo312/Message-Board-of-WeChat#5]

**Comment by igo312** [comment]
如果是在审核的时候被以这样的理由拒绝
通常来讲可以申诉一下，讲清楚自己的用途，截图等等保证自己只是用于留言板等
TX审批环节也是有点迷的，会因人而异，同时有时候严格有时候宽松
所以申诉和过段时间重新上线可能是比较好的方法

**Comment by Ezereal** [comment]
> 如果是在审核的时候被以这样的理由拒绝
> 通常来讲可以申诉一下，讲清楚自己的用途，截图等等保证自己只是用于留言板等
> TX审批环节也是有点迷的，会因人而异，同时有时候严格有时候宽松
> 所以申诉和过段时间重新上线可能是比较好的方法

好的 明白了 多谢大佬！

**Comment by igo312** [comment]
@Ezereal 希望能帮到你呢。我把问题关闭了，什么疑问都欢迎你再重启这个问题。

**Comment by Ezereal** [comment]
好的 非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "igo312/Message-Board-of-WeChat"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月23日(星期三) 晚上7:07
收件人:&nbsp;"igo312/Message-Board-of-WeChat"<Message-Board-of-WeChat@noreply.github.com&gt;;
抄送:&nbsp;"793532302@qq.com"<793532302@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [igo312/Message-Board-of-WeChat] 请问一下关于留言功能属于社交范畴，只有企业资质的小程序号才可以发布这个问题你是怎么解决的呢？ (#5)





 
@Ezereal 希望能帮到你呢。我把问题关闭了，什么疑问都欢迎你再重启这个问题。
