### ISSUE TITLE
ola的 图片，但没看到留言啥的功能，这个是不是已经算正常了？

### ISSUE THREAD

**Issue by linkboy2007** [igo312/Message-Board-of-WeChat#6]
hi 在github上看到你的小程序。下载了微信的开发工具，然后把代码上传了。目前还在审核中。

没有改任何代码，手机目前测试显示，ola的 图片，但没看到留言啥的功能，这个是不是已经算正常了？后面文章里面调用会显示留言功能？

**Comment by igo312** [comment]
hello

那是欢迎界面呢，考虑到打开小程序直接进入留言板涉及隐私的问题，因此我把页面的初始界面导向了ola，这样在直接打开小程序将无法进入任何留言板。如果你希望进入小程序跳转到留言板，可以修改`app.json`中的`pages`，将`<....>/comment`放在最前方即可。

至于在文章调用，只要遵守下面规则应该没问题的
>4.在绑定过程中会提示添加小程序页面路径，请使用pages/post/comment/comment?idx=(输入你自己的编号)进行绑定

**Comment by linkboy2007** [comment]
"pages": [
    "pages/post/comment/comment",
    "pages/post/welcome/welcome",

    "pages/index/index",
    "pages/openapi/openapi"
  ],

修改了位置以后 ，点击 写留言 没有反映

**Comment by linkboy2007** [comment]
WAService.js:1 Error: errCode: -404011 cloud function execution error | errMsg: cloud.callFunction:fail requestID , cloud function service error code -501000, error message Environment not found; at cloud.callFunction api; 
    at new u (WAService.js:1)
    at d (WAService.js:1)
    at f (WAService.js:1)
    at Function.success (WAService.js:1)
    at WAService.js:1
    at C (WAService.js:1)
    at i.<anonymous> (WAService.js:1)
    at i.emit (WAService.js:1)
    at Rs (WAService.js:1)
    at WAService.js:1

**Comment by linkboy2007** [comment]
现在不能    "pages/post/welcome/welcome",  放前面。小程序会审核不通过。说点击没内容 ，没反映。但是 "pages/post/comment/comment", 放前面，点击留言没内容。。

**Comment by igo312** [comment]
>WAService.js:1 Error: errCode: -404011 cloud function execution error | errMsg: cloud.callFunction:fail requestID , cloud function service error code -501000, error message Environment not found; at cloud.callFunction api;...

这个是什么错误呢？

如果是要发布小程序，在测试路径上应填写`pages/post/comment/comment?idx=(你的id)`，如是把`welcome`页面放在最前方发布遇到类似的情况，建议在审核提交时将具体情况说明或者申诉。另外一种是等过段时间再提交，可能遇到审核较严格的人员也说不定

**Comment by linkboy2007** [comment]
> > WAService.js:1 Error: errCode: -404011 cloud function execution error | errMsg: cloud.callFunction:fail requestID , cloud function service error code -501000, error message Environment not found; at cloud.callFunction api;...
> 
> 这个是什么错误呢？
> 
> 如果是要发布小程序，在测试路径上应填写`pages/post/comment/comment?idx=(你的id)`，如是把`welcome`页面放在最前方发布遇到类似的情况，建议在审核提交时将具体情况说明或者申诉。另外一种是等过段时间再提交，可能遇到审核较严格的人员也说不定


pages/post/comment/comment?idx=(你的id)   id是指   小程序的id   wxceXXXXXXXX 吗？


我修改了以后  把 welcome放前面，依然点击 留言没有反映。。

**Comment by igo312** [comment]
`id`可以是任意的。

如果是在留言板的界面，点击留言应该是有反应的。或者你可以尝试真机调试看看。

**Comment by linkboy2007** [comment]
VM13:2 Error: cloud.callFunction:fail -404011 cloud function execution error. 
云函数调用失败(callid 1616146918840-0.8909453921152244):
-501000 Environment not found

目前看好像是这个问题。。

**Comment by igo312** [comment]
请问云函数部署了么？ 似乎是没有使用云开发的指令呢

**Comment by linkboy2007** [comment]
是的 就是不太清楚怎么部署

具体的云开发函数部署见[3]

然后发现 3 没写。。。。

**Comment by igo312** [comment]
你好，我已更新。具体见[云开发模版](https://developers.weixin.qq.com/miniprogram/dev/wxcloud/basis/quickstart.html#_1-%E6%96%B0%E5%BB%BA%E4%BA%91%E5%BC%80%E5%8F%91%E6%A8%A1%E6%9D%BF)

**Comment by linkboy2007** [comment]
是在不好意思反复打扰，目前看起来 云部署应该是正常的。cloudfunctions 上有一个 ☁的标志，云开发里面也能看到有访问记录。
就是不能留言。。我能加你qq 或者微信咨询吗？

**Comment by linkboy2007** [comment]
Error: errCode: -404011 cloud function execution error | errMsg: cloud.callFunction:fail requestID , cloud function service error code -501000, error message 找不到对应的FunctionName.; at cloud.callFunction api; 
    at new u (WAService.js:1)
    at d (WAService.js:1)
    at f (WAService.js:1)
    at Function.success (WAService.js:1)
    at WAService.js:1
    at C (WAService.js:1)
    at i.<anonymous> (WAService.js:1)
    at i.emit (WAService.js:1)
    at Rs (WAService.js:1)
    at WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
a @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
l @ WAService.js:1
(anonymous) @ WAService.js:1
Promise.catch (async)
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
exportAPI.<computed> @ WAService.js:1
fail @ item-post.js? [sm]:211
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
a @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
l @ WAService.js:1
(anonymous) @ WAService.js:1
Promise.catch (async)
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
exportAPI.<computed> @ WAService.js:1
_callee$ @ item-post.js? [sm]:164
L @ regenerator.js:1
(anonymous) @ regenerator.js:1
t.<computed> @ regenerator.js:1
asyncGeneratorStep @ asyncToGenerator.js:1
c @ asyncToGenerator.js:1
(anonymous) @ asyncToGenerator.js:1
(anonymous) @ asyncToGenerator.js:1
commentFromCloud @ item-post.js? [sm]:242
_callee$ @ comment.js? [sm]:371
L @ regenerator.js:1
(anonymous) @ regenerator.js:1
t.<computed> @ regenerator.js:1
asyncGeneratorStep @ asyncToGenerator.js:1
c @ asyncToGenerator.js:1
(anonymous) @ asyncToGenerator.js:1
(anonymous) @ asyncToGenerator.js:1
initInfo @ comment.js? [sm]:369
onLoad @ comment.js? [sm]:390
(anonymous) @ WAService.js:1
p.__callPageLifeTime__ @ WAService.js:1
Tt @ WAService.js:1
(anonymous) @ WAService.js:1
xt @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
i.emit @ WAService.js:1
emit @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
c @ VM8 asdebug.js:1
l @ VM8 asdebug.js:1
(anonymous) @ VM8 asdebug.js:1
f @ VM8 asdebug.js:1
g @ VM8 asdebug.js:1
(anonymous) @ VM8 asdebug.js:1
_ws.onmessage @ VM8 asdebug.js:1
Show 28 more frames

**Comment by linkboy2007** [comment]
清除所有缓存 好了。谢谢
